### PR TITLE
Specify numpy as a build dependency.

### LINKED ISSUE #31: Add numpy as dependancy when installing package
The package should automatically install its dependacies, including Numpy.
```Collecting batman-package (from transitleastsquares)
  Downloading https://files.pythonhosted.org/packages/f3/59/a1ca181cafde7c99099da61cd578efc90c4319899a0c31c72241d50b0783/batman-package-2.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-05nyoioa/batman-package/setup.py", line 4, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-05nyoioa/batman-package/```

### PR DESCRIPTION
**Pull request by jdmoorman**
Resolves #31

### CODE REVIEW

**Comment by dtn5ah** [comment]
Any update on this PR? Colleague of mine is using this project and we would like to have our requirements file be self sufficient :)

**Comment by lkreidberg** [comment]
thanks for this PR- just merged! sorry I was so slow - I moved to Germany a couple weeks ago :)

**Comment by dtn5ah** [comment]
Fantastic, thanks @jdmoorman for the fix and @lkreidberg for the merge! Is there a chance we will see a new release pushed up to PyPI, or should we be installing straight from this repo?

**Comment by jdavies-st** [comment]
Echo the request to see a new patch release on `pypi` with the `pyproject.toml` so that

```
pip install batman-package
```

works without having to have `numpy` preinstalled.  This is especially important where other packages depend on `batman-package`, but don't necessarily install `numpy` themselves.  👍

**Comment by lkreidberg** [comment]
Done! Sorry for the delay - I just moved to Germany.

**Comment by jdavies-st** [comment]
Thank you very much!  Much appreciated.

**Pull request merged**
